version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - cd frontend
      - npm install
  build:
    commands:
      - echo echo $PWD
      - npm run build
  post_build:
    commands:
    # - cd ../frontend 
      - echo "Uploading to S3.."
      - aws s3 cp dist s3://react-test-12311 --recursive
      - echo "Done."

artifacts:
  files:
    - frontend/dist/**/*/
  discard-paths: no


